### ISSUE TITLE
[view] render metadata with markdown

### ISSUE THREAD

**Issue by bitbeckers** [hypercerts-org/hypercerts-app#141]
We have hypercerts in our collection that have descriptions rendered with markdown. We used to support this in the previous app and for future-proofing we also need this in the new app.

Example of hypercert with markdown: https://testnet.hypercerts.org/hypercerts/11155111-0xa16DFb32Eb140a6f3F2AC68f41dAd8c7e83C4941-137474076236059139239203341402434357428224

**Comment by 0xRowdy** [comment]
I've completed the work for this ticket.

I believe it is worth noting that this will increase the JS bundle by roughly 45.4 kB. That is due to the react-markdown package that I installed to complete the work. If markdown will be utalized in the future it could be worth it. If it is a one off edge case it might not.

**Comment by bitbeckers** [comment]
Thanks, also for the feedback on bundle size. In the furute we'll also allow markdown as input, this intermediate step ensures backwards compatibility
