### ISSUE TITLE
[UI] add "My hypercerts" to navbar and remove dropdown from create

### ISSUE THREAD

**Issue by holkexyz** [hypercerts-org/hypercerts-app#191]
1. It feels like a lot of stuff is in the profile, but it isn't that obvious.

Let's add "My hypercerts" to the navbar after "Create" before "Docs"

Let's make sure that the longer bar works when the window is small (without being in mobile mode yet)

2. let's remove the dropdown from the create button as long as there is only one item

![Image](https://github.com/user-attachments/assets/b75d0b22-e2cb-4278-b212-11426e4a2988)

**Comment by holkexyz** [comment]
3. The "Create hypercert" links to the explore page

**Comment by bitbeckers** [comment]
Updated in #224 except for the Switzer font. @thebeyondr you're implementing the font?

The issue why all font looked the same was becasue I sloppy copied the initial link to create the other, which checked on the current site path. In other words, they all looked the same because the checks on path failed for all of them. In the referenced PR, the active page is black while the non-active pages have 70% opacity
